language: rust
rust:
  - nightly
before_install:
  - nvm install node
  - nvm use node
  - nvm install firebase-tools
after_success: export RUST_BACKTRACE=1 && cargo run && firebase deploy --token "$FIREBASE_TOKEN"
